#!/bin/sh

: ${OPSYS:=`uname -s`}
: ${NM:=nm}

case ${OPSYS} in
    *BSD|DragonFly)
	${NM} "$@" |
	grep -Ev 'fini|init' |
	awk '$2=="T" {print "symbol " $3}'
	;;
    SunOS)
	${NM} "$@" |
	grep -Ev 'fini|init' |
	awk 'NF==4 && $2=="T" {print "symbol " $1}'
	;;
    Linux)
	${NM} "$@" |
	grep -Ev 'fini|init' |
	awk 'NF==4 && $2 ~ /^[DT]$/ {print "symbol " $1}'
	;;
esac
