MKC_REQUIRE_HEADERS  =	trtrtr.h sys/brbrbr.h
MKC_REQUIRE_PROGS    =	trtrtr   brbrbr
MKC_REQUIRE_FUNCLIBS =	trtrtr   brbrbr:dl
MKC_REQUIRE_DEFINES  =	TRTRTR   BRBRBR:sys/time.h
MKC_REQUIRE_TYPES    =	trtrtr_t brbrbr_t:sys/time.h
MKC_REQUIRE_VARS     =	v_trtrtr v_brbrbr:sys/time.h
MKC_REQUIRE_MEMBERS  =	trtr.trtr_t:string.h brbr.brbr_t:sys/time.h
MKC_REQUIRE_FUNCS2   =	trtrtr:sys/time.h
MKC_REQUIRE_FUNCS3   =	brbrbr
MKC_REQUIRE_CUSTOM   =	test1
MKC_CUSTOM_FN.test1  =	test1.c

.include "test.mk"
.include <mkc.mk>
