.\" Written by by Aleksey Cheusov (vle@gmx.net)
.\" ------------------------------------------------------------------
.TH DICTZIP 1 "May 16, 2010" "" ""
.SH NAME
dictd \- dictionary protocol server
.SH SYNOPSIS
.B "dictzip"
.br
.SH DESCRIPTION
.B dictzip
is just a fake application
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
