PROG    =	prog2

WARNS   =	4

MKC_REQD =	0.10.0

# Additional CPPFLAGS may be specified for a particular source file
CPPFLAGS_prog2.c +=	-DNUM=2

check:
	@: do something useful

.include <mkc.prog.mk>
