.\"	$NetBSD$
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.TH FSCK_SUPERFS 8 "Jul 23, 2010"
.SH NAME
fsck_superfs \- fsck utility for superfs file system
.SH DESCRIPTION
.B fsck_superfs
is one of mk-c examples
.SH SEE ALSO
.BR fsck(8) , mkfs(8)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
