.\" Written by Aleksey Cheusov (vle@gmx.net)
.\" ------------------------------------------------------------------
.TH DICTD 1 "May 16, 2010" "" ""
.SH NAME
dictd \- dictionary protocol server
.SH SYNOPSIS
.B "dictd"
.br
.SH DESCRIPTION
.B dictd
is just a fake application
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
