MKC_COMMON_HEADERS+=	string.h

MKC_CHECK_HEADERS+=	sys/time.h string.h

MKC_CHECK_FUNCLIBS+=	strcpy sqrt:m

MKC_CHECK_DEFINES+=	__GNUC__

MKC_CHECK_VARS+=	errno:errno.h

MKC_CHECK_FUNCS2+=	strcmp:string.h
MKC_CHECK_FUNCS3+=	strcpy

MKC_CHECK_SIZEOF+=	int long-long void* size_t:string.h

vars+=	HAVE_HEADER.sys_time_h HAVE_HEADER.string_h \
	HAVE_FUNCLIB.strcpy HAVE_FUNCLIB.sqrt.m \
	HAVE_DEFINE.__GNUC__ \
	HAVE_FUNC2.strcmp.string_h HAVE_FUNC3.strcpy \
	SIZEOF.int SIZEOF.long_long SIZEOF.voidP SIZEOF.size_t.string_h

all:
.for i in ${vars}
	@echo ${i}=${${i}} | sed '/SIZEOF/ s|[0-9][0-9]*|n|'
.endfor

.include "./configure.mk"
