#!/bin/sh

############################################################
# Copyright (c) 2012 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

sed 's,/[^ ]*/,/path/to/,' "$@"
