.\"	$NetBSD$
.\"
.\" Copyright (c) 2009-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VS \" Verbatim Start
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH MKC_CHECK_CUSTOM 1 "Nov 22, 2009" "" ""
.SH NAME
mkc_check_custom \- run user's custom checks.
.SH SYNOPSIS
.BI mkc_check_custom " [-r] <file>"
.br
.BI mkc_check_custom " -h"
.SH DESCRIPTION
.B mkc_check_custom
takes a
.I file
and tries to compile or runs it. If
.I file
is an executable file,
.B mkc_check_custom
runs it and outputs 1 if it succeeded or 0 otherwise.
If
.I file
is not executable,
.B mkc_check_custom
tries to compile and (if
.I -r
applied ) run a generated executable. Again, if compilation/run succeeded,
1 is output, otherwise -- 0. What type of compiler to use depend on
.I file
extension. '.c' corresponds to
.I ${CC}
(C language), '.cc', '.cxx', '.C' and '.cpp' correspond to
.I ${CXX}
(C++ language), '.f' -- to
.I ${FC}
(Fortran).
.SH OPTIONS
.TP
.B "-h"
display help message
.SH ENVIRONMENT
.TP
.B CC
C compiler
.TP
.B CXX
C++ compiler
.TP
.B FC
Fortran compiler
.TP
.B CPPFLAGS
Preprocessor flags for C and C++
.TP
.B CFLAGS
Compilation flags for C
.TP
.B CXXFLAGS
Compilation flags for C++
.TP
.B FFLAGS
Compilation flags for Fortran
.TP
.B MKC_VERBOSE
If set to 1, verbose messages are output to stderr.
.TP
.B MKC_SHOW_CACHED
If set to 1 and MKC_VERBOSE is set to 1, cached results
are output to stderr.
.TP
.B MKC_CACHEDIR
Directory where temporary and cache files are created.
If unset they are created in a current directory.
.TP
.B MKC_NOCACHE
All results are cached unless MKC_NOCACHE variable is set
to 1.
.TP
.B MKC_DELETE_TMPFILES
If set to 1, temporary files are removed.
.SH EXAMPLES
.VS
   mkc_check_custom alloca_in_stdlib.c
   mkc_check_custom custom_checks/cxx_foo_test.cc
   mkc_check_custom /full/path/to/yacc_need_liby
.VE
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
