#!/bin/sh

############################################################
# Copyright (c) 2009-2010 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e
test $# -eq 2

prefix="$1"
objdir="$2"

LC_ALL=C
export LC_ALL

grep -v CVS |
grep -v '~$' |
sed -e "s,$objdir,/objdir," \
    -e "s,$prefix,/prefix," \
    -e "s,/usr/pkg,/prefix," \
    -e "s,/usr,/prefix," \
    -e 's/\([.][^ ]*\)[.]dylib/.so\1/' \
    -e 's/[.]dylib/.so/' \
    -e 's/[.]exe//' \
    -e 's,lua/[0-9]*[.][0-9]*,lua/X.Y,' \
    -e 's/[.]sl/.so/' -e /so_locations/d|
sort
