.\"	$NetBSD$
.\"
.\" Copyright (c) 2009 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VS \" Verbatim Start
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH MKC_CHECK_PROG 1 "Aug 29, 2009" "" ""
.SH NAME
mkc_check_prog \- detects presense of header file.
.SH SYNOPSIS
.BI mkc_check_prog " <progname>"
.br
.BI mkc_check_prog " -h|--help"
.SH DESCRIPTION
.B mkc_check_prog
takes a name and looks for the file with that name which would be
executable.  Executable is searched for along the user's PATH.
If appropriate executable is found, a path to it is printed.
Otherwise, an error message is printed and
.B mkc_check_prog
exits with error.
.SH OPTIONS
.TP
.B "-h|--help"
display help message
.SH ENVIRONMENT
.TP
.B PATH
List of colon-separated directories.
.TP
.B MKC_VERBOSE
If set to 1, verbose messages are output to stderr.
.TP
.B MKC_SHOW_CACHED
If set to 1 and MKC_VERBOSE is set to 1, cached results
are output to stderr.
.TP
.B MKC_CACHEDIR
Directory where temporary and cache files are created.
If unset they are created in a current directory.
.TP
.B MKC_NOCACHE
All results are cached unless MKC_NOCACHE variable is set
to 1.
.TP
.B MKC_DELETE_TMPFILES
If set to 1, temporary files are removed.
.SH EXAMPLES
.VS
   mkc_check_prog gawk
   mkc_check_prog c++
   mkc_check_prog lua
.VE
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
