#!/bin/sh

############################################################
# Copyright (c) 2009-2010 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

sed '/^checking / s|^\(.*\) [^ ]*[.][.][.].*$|\1 mmm... nnn|' "$@"
