#!/bin/sh

############################################################
# Copyright (c) 2009 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

##################################################
# options
usage (){
    cat <<EOF
mkc_check_prog detects presense of program file.

Usage: mkc_check_prog progname

Examples:
   mkc_check_prog lua
   mkc_check_prog gawk
   mkc_check_prog runawk
EOF
}

if test "$1" = '-h' -o "$1" = '--help'; then
    usage
    exit 0
fi
if test $# -ne 1; then
    usage
    exit 1
fi

##################################################
# initializing

pathpart=prog_`echo $1 | tr /. __`

. mkc_check_common.sh

##################################################
# test

check_itself (){
    mkc_which -x "$1" 2>"${tmperr}"
}

check_and_cache "checking for program $1" "$cache" "$1"

##################################################
# clean-ups

cleanup

##################################################
# finishing

if test -n "$ret"; then
    printme "$ret\n" 1>&2
else
    printme 'NOT FOUND\n' 1>&2
fi

echo $ret
