.\"	$NetBSD$
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH MKC_CHECK_DECL 1 "Mar 15, 2009" "" ""
.SH NAME
mkc_check_decl \- checks for define, function, variable or type.
.SH SYNOPSIS
.BI mkc_check_decl " <define|variable|func[0-9]|type>" " <what>" " [includes...]"
.br
.BI mkc_check_decl " -h|--help"
.SH DESCRIPTION
.B mkc_check_decl
detects presense of define, variable, function or type
in system header files by compiling a test program.
As a result it prints either 1 (true) or 0 (false) to stdout.
.SH OPTIONS
.TP
.B "-h|--help"
display help message
.SH ENVIRONMENT
.TP
.B CC
Compiler. By default
.I cc
is used.
.TP
.B CPPFLAGS, CFLAGS
Options passed to the compiler, for example -I for additional directories
that contain header files.
.TP
.B MKC_VERBOSE
If set to 1, verbose messages are output to stderr.
.TP
.B MKC_SHOW_CACHED
If set to 1 and MKC_VERBOSE is set to 1, cached results
are output to stderr.
.TP
.B MKC_COMMON_HEADERS
List of header files to add to .c test program.
.TP
.B MKC_CACHEDIR
Directory where temporary and cache files are created.
If unset they are created in a current directory.
.TP
.B MKC_NOCACHE
All results are cached unless MKC_NOCACHE variable is set
non-empty value
.TP
.B MKC_DELETE_TMPFILES
If set to 1, temporary files are removed.
.SH EXAMPLES
.VB
   mkc_check_decl define __GCC__
   mkc_check_decl define RTLD_LAZY dlfcn.h
   mkc_check_decl variable sys_errlist errno.h
   mkc_check_decl variable __malloc_hook malloc.h
   mkc_check_decl func3 poll poll.h
   mkc_check_decl func2 fgetln stdio.h
   mkc_check_decl type mbstate_t wchar.h
   mkc_check_decl type long-long
.VE
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
