.include "../features.mk"

PROGS =			test_features1 test_features2 test_features3 
SRCS.test_features1 =	test_features1.cxx
SRCS.test_features2 =	test_features2.cxx
SRCS.test_features3 =	test_features3.cxx

.include <mkc.mk>
