SHRTOUT           =	no
NOEXPORT_VARNAMES =	MKC_CACHEDIR
EXPORT_VARNAMES   =	SHRTOUT

BUILTINSDIR       =	${OBJDIR_custom}
.export BUILTINSDIR

SUBDIR  +=	configure_test
SUBDIR  +=	mkinstall
SUBDIR  +=	../examples
SUBDIR  +=	mkshlib
SUBDIR  +=	mkstaticlib
SUBDIR  +=	mkpiclib
SUBDIR  +=	mkprofilelib
SUBDIR  +=	mkdll
SUBDIR  +=	pkg_config_0
SUBDIR  +=	pkg_config_1
SUBDIR  +=	pkg_config_1_1
SUBDIR  +=	pkg_config_2
SUBDIR  +=	lua_dirs
SUBDIR  +=	rec_makefiles
SUBDIR  +=	reqd
SUBDIR  +=	reqd2
SUBDIR  +=	reqd3
SUBDIR  +=	reqd4
SUBDIR  +=	reqd_clean_cache
SUBDIR  +=	intexts_cleantrg
SUBDIR  +=	require_prototype
SUBDIR  +=	test_subprj_dash
SUBDIR  +=	test_mkc_vs_PROG
SUBDIR  +=	test_mkc_vs_LIB
SUBDIR  +=	test_mkc_vs_SUBDIR
SUBDIR  +=	test_mkc_vs_SUBPRJ
SUBDIR  +=	endianess
SUBDIR  +=	create_cachedir

.include <mkc.mk>
