NOEXPORT_VARNAMES=	MKC_CACHEDIR

SUBDIR	+=	configure_test
SUBDIR  +=	../examples
SUBDIR  +=	mkshlib
SUBDIR  +=	mkstaticlib
SUBDIR  +=	mkpiclib
SUBDIR  +=	mkprofilelib
SUBDIR  +=	mkdll
SUBDIR  +=	pkg-config-0
SUBDIR  +=	pkg-config-1
SUBDIR  +=	pkg-config-2
SUBDIR  +=	lua_dirs
SUBDIR  +=	rec_makefiles

.include <mkc.mk>
