#!/bin/sh

############################################################
# Copyright (c) 2009-2010 by Aleksey Cheusov
#
# See LICENSE file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

sed -e '/checking for C\([+]\)* compiler type/ s|[.][.][.] .*|... mmm nnn|'
