#!/bin/sh

############################################################
# Copyright (c) 2012 by Aleksey Cheusov
#
# See LICENSE file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

sed -e 's,/[^ ]*/,/path/to/,' \
    -e 's/\([.][^ ]*\)[.]dylib/.so\1/' \
    -e 's/[.]bundle/.so/' \
    "$@"
