#!/bin/sh

############################################################
# Copyright (c) 2009-2010 by Aleksey Cheusov
#
# See LICENSE file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

sed -e '/checking C\([+]\)* compiler type/ s|[.][.][.] .*|... mmm nnn|' "$@" |
grep -Ev 'ld: warning:.*was built for newer macOS version'

