# main code
SUBDIR +=	libhello1
SUBDIR +=	libhello2
SUBDIR +=	.WAIT
SUBDIR +=	hello

MKC_REQD =	0.11.0

# for regression test only
_THISDIR_ =
.export _THISDIR_

#
.include "test.mk"
.include "version.mk"
.include <mkc.subdir.mk>
