PROG      = program
INSCRIPTS = lalala foo
INFILES   = bar
TEXINFO   = program.texinfo
SCRIPTS   = baz shell_script
FILES     = file1 file2
MAN       = program.1
MKCATPAGES= yes
MLINKS    = bar1 bar2
SYMLINKS  = foo1 foo2
LINKS     = baz1 baz2
INCS      = qqq.h
DPSRCS    = zzz.c

.include <mkc.mk>
