INSCRIPTS  =	endianness prog_bison prog_flex prog_gawk prog_gm4 prog_gmake \
		prog_mkdep prog_nbmkdep
SCRIPTS    =	${INSCRIPTS}
SCRIPTSDIR =	${BUILTINSDIR}

FILES      =	easy.c easy.cc
FILESDIR   =	${SCRIPTSDIR}

.include <mkc.mk>
