#!/bin/sh

############################################################
# Copyright (c) 2009 by Aleksey Cheusov
#
# See LICENSE file in the distribution.
############################################################

LC_ALL=C
export LC_ALL

pathpart=' ' # fake
. mkc_check_common.sh

find_n_match gm4 --version 'gnu m4' ||
find_n_match  m4 --version 'gnu m4' ||
echo ''
