#!/bin/sh

############################################################
# Copyright (c) 2014 by Aleksey Cheusov
#
# See LICENSE file in the distribution.
############################################################

LC_ALL=C
export LC_ALL

pathpart=' ' # fake
. mkc_check_common.sh

find_n_match  make '-f /dev/null --version' 'gnu make'
find_n_match gmake '-f /dev/null --version' 'gnu make'

echo ''
