.\" Written by Aleksey Cheusov (vle@gmx.net)
.\" ------------------------------------------------------------------
.TH DICT 1 "May 16, 2010" "" ""
.SH NAME
dict \- dictionary protocol client
.SH SYNOPSIS
.B "dict"
.br
.SH DESCRIPTION
.B dict
is just a fake application
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
