.\" Written by Aleksey Cheusov (vle@gmx.net)
.\" ------------------------------------------------------------------
.TH DICTFMT 1 "May 16, 2010" "" ""
.SH NAME
dictfmt \- dictionary formatting utility
.SH SYNOPSIS
.B "dictfmt"
.br
.SH DESCRIPTION
.B dictfmt
is just a fake application
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
