LIB=		cxxlib

WARNS=4

SHLIB_MAJOR=	1
SHLIB_MINOR=	0
SHLIB_TEENY=	5

INCS=		hello_msg.h impl/hello_msg1.h impl/hello_msg2.h

INCSSRCDIR=	include

SRCS=		hello_msg1.cpp hello_msg2.cpp

.include <mkc.lib.mk>
