SUBDIR+=	hello_world
SUBDIR+=	hello_scripts
SUBDIR+=	hello_sizeof
SUBDIR+=	subprojects
SUBDIR+=	hello_compilers
SUBDIR+=	hello_dlopen
SUBDIR+=	hello_glib2
SUBDIR+=	hello_strlcpy

.include <mkc.subdir.mk>
