=head1 NAME

xxzip - super-puper compression utility

=head1 SYNOPSIS

B<xxzip> I<[options]> I<[files...]>

B<xxunzip> I<[options]> I<[files...]>

B<xxzcat> I<[options]> I<[files...]>

=head1 DESCRIPTION

bla bla bla

=head1 OPTIONS

=over 6

=item B<-h>

Display help information.

=item B<-c>

Output to the standard output stream

=item B<-d>

This option selects decompression rather than compression.

=back

=head1 AUTHOR

Copyright (c) 2010 Aleksey Cheusov <vle@gmx.net>

=head1 HOME

L<http://sourceforge.net/projects/mk-configure>

=head1 SEE ALSO
L<mk-configure(7)>
