.\"	$NetBSD$
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.TH SHELL_FUNCS 7 "Aug 29, 2008"
.SH NAME
shell_funcs \- collection of function written in shell
.SH DESCRIPTION
.B shell_funcs
is a collection...
.SH SEE ALSO
.BR sh(1) ,
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
