PROG     =	qux
MAN      =	qux.1
FILES    =	foo
SCRIPTS  =	bar
INCS     =	baz.h
LINKS    =	${BINDIR}/qux ${BINDIR}/qux2
SYMLINKS =	${BINDIR}/foo ${BINDIR}/foo2
MLINKS   =	qux.1 qux2.1
TEXINFO  =	qux.info

.include "test.mk"
.include <mkc.mk>
