.\"	$NetBSD$
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.TH MKFS_SUPERFS 8 "Jul 23, 2010"
.SH NAME
mkfs_superfs \- mkfs utility for superfs file system
.SH DESCRIPTION
.B mkfs_superfs
is one of mk-c examples
.SH SEE ALSO
.BR mkfs(8) , fsck(8)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
