SUBPRJ  =	libcommon:dict
SUBPRJ +=	libcommon:dictd
SUBPRJ +=	libcommon:dictzip
SUBPRJ +=	libcommon:dictfmt
SUBPRJ +=	libmaa:dict
SUBPRJ +=	libmaa:dictd
SUBPRJ +=	libmaa:dictzip
SUBPRJ +=	libmaa:dictfmt
SUBPRJ +=	libdz:dictzip

# Subproject "doc" has no dependencies
SUBPRJ +=	doc
# and is not built by default
SUBPRJ_DFLT =	dict dictd dictzip dictfmt

.include "test.mk"
.include <mkc.subprj.mk>
