SUBPRJ=		libcommon:dict
SUBPRJ+=	libcommon:dictd
SUBPRJ+=	libcommon:dictzip
SUBPRJ+=	libcommon:dictfmt
SUBPRJ+=	libmaa:dict
SUBPRJ+=	libmaa:dictd
SUBPRJ+=	libmaa:dictzip
SUBPRJ+=	libmaa:dictfmt
SUBPRJ+=	libdz:dictzip
SUBPRJ+=	dict dictd dictfmt dictzip # useless here but allowed

.include <mkc.own.mk>
.include "test.mk"
.include <mkc.subprj.mk>
