#!/bin/sh

############################################################
# Copyright (c) 2009 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

##################################################

pathpart=endianess
. mkc_check_common.sh

trap "rm -f $tmpc $tmpo" 0

cat > "$tmpc" <<EOF
#include <sys/types.h>
#include <sys/param.h>

int main (int argc, char **argv)
{
#if BYTE_ORDER == _LITTLE_ENDIAN
   return 0;
#else
   error
#endif
}
EOF

if $CC -o "$tmpo" -c $CFLAGS $CPPFLAGS "$tmpc"; then # 2>/dev/null; then
    echo little
    exit 0
fi

exit 5

cat > "$tmpc" <<EOF
#include <sys/types.h>
#include <sys/param.h>

int main (int argc, char **argv)
{
#if BYTE_ORDER == _BIG_ENDIAN
   return 0;
#else
   error
#endif
}
EOF

if $CC -o "$tmpo" -c $CFLAGS $CPPFLAGS "$tmpc" 2>/dev/null; then
    echo little
    exit 0
fi

echo unknown
exit 0
