#!/bin/sh

############################################################
# Copyright (c) 2009 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

LC_ALL=C
export LC_ALL

pathpart=' ' # fake
. mkc_check_common.sh

find_n_match bison --version 'bison'
find_n_match  yacc --version 'bison'

echo ''
