#!/bin/sh

############################################################
# Copyright (c) 2009 by Aleksey Cheusov
#
# See COPYRIGHT file in the distribution.
############################################################

set -e

LC_ALL=C
export LC_ALL

##################################################

pathpart=yacc_need_liby
. mkc_check_common.sh

tmpy=${tmpc%.c}.y

cat > "$tmpy" <<'EOF'
%{
#include <ctype.h>
#include <stdio.h>
#define YYSTYPE int
%}

%token NUMBER
%left  '+' '-'

%%

lines : lines expr '\n' { printf ("%i\n", $2); }
      | lines '\n'
      |
      ;

expr : expr '+' expr { $$ = $1 + $3; }
     | expr '-' expr { $$ = $1 - $3; }
     | NUMBER
     ;

%%

yylex (){
	/**/
	return '+';
}
EOF

if test -z "$YACC"; then
    echo 'Set YACC first!' 1>&2
    exit 1
fi

"$YACC" -o "$tmpc" "$tmpy"

if $CC -o "$tmpexe" $CFLAGS $CPPFLAGS $LDFLAGS "$tmpc" $LDADD 1>&2; then
    echo 0
else
    rm -f "$tmpexe"
    echo 1
fi
