MKC_FEATURES =	strlcat strlcpy getline progname fgetln err warn libm \
    getdelim strndup libdl RB SLIST SIMPLEQ STAILQ LIST TAILQ CIRCLEQ #SPLAY

PROG =		test_features
SRCS =		test_features.cxx

.include <mkc.mk>
