.\"	$NetBSD$
.\"
.\" Copyright (c) by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VS \" Verbatim Start
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH MKC_CHECK_SIZEOF 1 "Mar 31, 2019" "" ""
.SH NAME
mkc_check_sizeof \- detects a sizeof(type).
.SH SYNOPSIS
.BI mkc_check_sizeof " [OPTIONS] type [headers...]"
.SH DESCRIPTION
.B mkc_check_sizeof
detects sizeof(
.I type
) by compiling a test program.
Compiled program is not executed, therefore
this check is ready for cross-compiling.
.I headers
is either a single header file or a list of headers, separated by comma.
.SH OPTIONS
.TP
.B "-h"
display help message
.SH ENVIRONMENT
.TP
.B CC
Compiler. By default
.I cc
is used.
.TP
.B CPPFLAGS, CFLAGS
Options passed to the compiler.
.TP
.B MKC_VERBOSE
If set to 1, verbose messages are output to stderr.
.TP
.B MKC_SHOW_CACHED
If set to 1 and MKC_VERBOSE is set to 1, cached results
are output to stderr.
.TP
.B MKC_CACHEDIR
Directory where temporary and cache files are created.
If unset they are created in a current directory.
.TP
.B MKC_NOCACHE
All results are cached unless MKC_NOCACHE variable is set
to 1.
.TP
.B MKC_DELETE_TMPFILES
If set to 1, temporary files are removed.
.SH EXAMPLES
.VS
   mkc_check_sizeof 'void*'
   mkc_check_sizeof long-long
   mkc_check_sizeof size_t stdlib.h
.VE
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
