.\"	$NetBSD$
.\"
.\" Copyright (c) 2009-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VS \" Verbatim Start
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH MKC_CHECK_FUNCLIB 1 "Dec 2, 2023" "" ""
.SH NAME
mkc_check_funclib \- detects presense of function in a library.
.SH SYNOPSIS
.BI mkc_check_funclib " <functionname>" " [libraries...]"
.br
.BI mkc_check_funclib " -h"
.SH DESCRIPTION
.B mkc_check_funclib
detects presense of function in a library
by compiling and linking a test program.
As a result it prints either 1 (true) or 0 (false) to stdout.
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.BI -d
Delete cache and temporary files.
.TP
.BI -D
Delete cache files.
.SH ENVIRONMENT
.TP
.B CC
Compiler. By default
.I cc
is used.
.TP
.B CPPFLAGS, CFLAGS
Options passed to the compiler, for example -I for additional directories
that contain header files.
.TP
.B LDFLAGS
Options passed to the linker (compiler, set by CC variable), for example,
-L/usr/local/lib
.TP
.B LDADD
Extra libraries, for example, -lm.
.TP
.B MKC_VERBOSE
If set to 1, verbose messages are output to stderr.
.TP
.B MKC_SHOW_CACHED
If set to 1 and MKC_VERBOSE is set to 1, cached results
are output to stderr.
.TP
.B MKC_CACHEDIR
Directory where temporary and cache files are created.
If unset they are created in a current directory.
.TP
.B MKC_NOCACHE
All results are cached unless MKC_NOCACHE variable is set
to 1.
.TP
.B MKC_DELETE_TMPFILES
If set to 1, temporary files are removed.
.SH EXAMPLES
.VS
   mkc_check_funclib dlopen dl
   mkc_check_funclib dlopen
   mkc_check_funclib strlcpy
   mkc_check_funclib select socket
.VE
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
